= AdonisTract image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License", link="https://opensource.org/licenses/Apache-2.0"] image:https://maven-badges.herokuapp.com/maven-central/com.woozooha/adonistrack/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.woozooha/adonistrack"]

Simple Java profiling tool.

* You can trace the call stack immediately.
* There is no need to write code to track method calls.
* Provide method call information(parameters, return, error and execution time).
* Compatible with the Spring Framework.
* The information is not intermixed with concurrent calls.
* Provides extension points to customize.

== Usage

=== 1. Add this library to your project

image:https://maven-badges.herokuapp.com/maven-central/com.woozooha/adonistrack/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.woozooha/adonistrack"]

=== 2. Configure your aspect to profile

* Create a aspect by extending the `ProfileAspect`, such as `AdonisTrackAspect.java`
* Configure `profilePointcut` and `executionPointcut` of the aspect by using pointcut expression.

[source,java,indent=0]
----
package com.woozooha.adonistrack.test.spring;

import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.stereotype.Component;

import com.woozooha.adonistrack.ProfileAspect;

@Aspect
@Component
public class AdonisTrackAspect extends ProfileAspect {

    /**
     * Fix this <code>@Pointcut</code> expression according to your situation. For
     * example, modify "com.woozooha.adonistrack.test.spring" to your application's
     * top-level package name "com.yourcompany.killerapp".
     */
    @Pointcut("execution(* com.woozooha.adonistrack.test.spring..*Controller.*(..))")
    protected void profilePointcut() {
    }

    /**
     * Fix this <code>@Pointcut</code> expression according to your situation. For
     * example, modify "com.woozooha.adonistrack.test.spring" to your application's
     * top-level package name "com.yourcompany.killerapp".
     */
    @Pointcut("execution(* *(..)) && (within(com.woozooha.adonistrack.test.spring..*) || within(com.woozooha.adonistrack.test.spring..*+))")
    protected void executionPointcut() {
    }

}
----

=== 3. Run your application with above aspect `AdonisTrackAspect.java`

[indent=0]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2019-04-17 13:45:18.014  INFO 254732 --- [           main] com.woozooha.hello.Application           : Starting Application ...
2019-04-17 13:45:33.663  INFO 254732 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
----

=== 4. Call your application and check the log

When your application is called via `GET /greeting?name=foo HTTP/1.1`

* This is the log when the execution was successful.

[indent=0]
----
----> com.woozooha.hello.GreetingController.greeting(hello) (8.85ms:100.00%)
    ----> com.woozooha.hello.GreetingService.greeting(hello) (5.05ms:100.00%)
        ----> com.woozooha.hello.GreetingRepository.find(hello) (2.72ms:99.35%)
        <---- hello (2.72ms:99.35%)
        ----> com.woozooha.hello.GreetingRepository.find(foo-hello) (0.02ms:0.65%)
        <---- hello (0.02ms:0.65%)
    <---- com.woozooha.hello.Greeting@50fdbf1d (5.05ms:100.00%)
<---- com.woozooha.hello.Greeting@50fdbf1d (8.85ms:100.00%)
----

* This is the log when the execution was failed.

[indent=0]
----
----> com.woozooha.hello.GreetingController.greeting(null) (0.34ms:100.00%)
    ----> com.woozooha.hello.GreetingService.greeting(null) (0.28ms:100.00%)
        ----> com.woozooha.hello.GreetingRepository.find(null) (0.22ms:100.00%)
        <<<<< java.lang.IllegalArgumentException: name can't be null. (0.22ms:100.00%)
    <<<<< java.lang.IllegalArgumentException: name can't be null. (0.28ms:100.00%)
<<<<< java.lang.IllegalArgumentException: name can't be null. (0.34ms:100.00%)
----

== License
AdonisTrack is Open Source software released under the Apache 2.0 license.
